version: "3.9"

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  app:
    build: .
    container_name: app-web
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_DB=mensajesdb
    depends_on:
      - mongo
    networks:
      - app-network
    volumes:
      - ./app:/usr/src/app

volumes:
  mongo-data:

networks:
  app-network:
